export const navContent = {
  es: {
    inicio: 'Inicio',
    nosotros: 'Nosotros',
    servicios: 'Servicios',
    galeria: 'Galería',
    noticias: 'Noticias',
    contacto: 'Contacto',
    ingresar: 'Ingresar',
    salir: 'Salir',
    dashboard: 'ENLACES RAPIDOS',
  },
  en: {
    inicio: 'Home',
    nosotros: 'About',
    servicios: 'Services',
    galeria: 'Gallery',
    noticias: 'News',
    contacto: 'Contact',
    ingresar: 'Sign in',
    salir: 'Logout',
    dashboard: 'Dashboard',
  },
}

export const homeContent = {
  es: {
    eyebrow: 'Formación académica con valores',
    title: 'Centro Escolar Dr. Hermogenes Alvarado',
    text: 'Institución educativa pública comprometida con la formación académica, moral y social de sus estudiantes.',
    ctaInfo: 'Admisiones e información',
    ctaSchool: 'Nuestra institución',
    commitment: 'Nuestro compromiso',
    commitmentTitle: 'Educando con calidad para construir un mejor futuro',
    commitmentText: 'Trabajamos diariamente para ofrecer un ambiente seguro, inclusivo y estimulante, donde cada estudiante pueda desarrollar sus habilidades académicas, sociales y humanas.',
    statsTitle: 'Datos que reflejan nuestro compromiso educativo',
  },
  en: {
    eyebrow: 'Academic education with values',
    title: 'Dr. Hermogenes Alvarado School Center',
    text: 'Public educational institution committed to academic, moral and social development.',
    ctaInfo: 'Request information',
    ctaSchool: 'Learn about the school',
    commitment: 'Our commitment',
    commitmentTitle: 'A close, organized educational community focused on learning',
    commitmentText: 'We work so school becomes a place where learning and coexistence build responsible students.',
    statsTitle: 'Numbers that speak about our commitment',
  },
}

export const pageContent = {
  es: {
    aboutTitle: 'Conócenos mejor',
    aboutIntro: 'Brindamos una educación integral, cercana y con valores, desde kínder hasta noveno grado, formando estudiantes responsables, preparados y con confianza para su futuro.',
    servicesTitle: 'Nuestros Servicios',
    servicesIntro: 'Ofrecemos apoyo académico, formación integral y actividades culturales y deportivas para acompañar el crecimiento de cada estudiante y su familia.',
    galleryTitle: 'Galería',
    galleryIntro: 'Conoce momentos especiales de la vida escolar, actividades y aprendizajes que fortalecen nuestra comunidad.',
    newsTitle: 'Noticias y Eventos',
    newsIntro: 'Mantente informado sobre actividades, logros, celebraciones y novedades del centro educativo.',
    contactTitle: 'Contacto',
    contactIntro: '',
  },
  en: {
    aboutTitle: 'Get to Know Us Better',
    aboutIntro: 'We provide comprehensive, close, and values-based education from kindergarten through ninth grade, helping students become responsible, prepared, and confident for their future.',
    servicesTitle: 'Our Services',
    servicesIntro: 'We offer academic support, holistic education, and cultural and sports activities to support the growth of each student and their family.',
    galleryTitle: 'Gallery',
    galleryIntro: 'Discover special moments from school life, activities, and learning experiences that strengthen our community.',
    newsTitle: 'News and Events',
    newsIntro: 'Stay informed about school activities, achievements, celebrations, and updates from the educational center.',
    contactTitle: 'Contact',
    contactIntro: 'If you have questions, need information, or want to get in touch, please complete the form and we will be happy to respond.',
  },
}

export const formContent = {
  es: {
    name: 'Nombre completo',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    subject: 'Asunto',
    category: 'Categoria',
    message: 'Mensaje',
    send: 'Enviar mensaje',
    sending: 'Contactanos ahora',
    save: 'Guardar',
    update: 'Actualizar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    title: 'Título',
    description: 'Descripción',
    image: 'URL de imagen',
    order: 'Orden',
    date: 'Fecha',
    time: 'Hora',
    news: 'Noticia',
    location: 'Ubicación',
    iframe: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3879.448792073009!2d-88.93974039999999!3d13.508027300000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f7cad62edce2e5d%3A0x6fc63c87d53b188!2zQ2VudHJvIEVzY29sYXIg4oCcRHIuIEhlcm3Ds2dlbmVzIEFsdmFyYWRv4oCd!5e0!3m2!1ses-419!2ssv!4v1785266083826!5m2!1ses-419!2ssv" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
  },
  en: {
    name: 'Full name',
    email: 'Email',
    phone: 'Phone',
    subject: 'Subject',
    category: 'Category',
    message: 'Message',
    send: 'Send message',
    save: 'Save',
    update: 'Update',
    cancel: 'Cancel',
    delete: 'Delete',
    title: 'Title',
    description: 'Description',
    image: 'Image URL',
    order: 'Order',
    date: 'Date',
    time: 'Time',
    news: 'News',
    location: 'Location',
    iframe: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3879.448792073009!2d-88.93974039999999!3d13.508027300000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f7cad62edce2e5d%3A0x6fc63c87d53b188!2zQ2VudHJvIEVzY29sYXIg4oCcRHIuIEhlcm3Ds2dlbmVzIEFsdmFyYWRv4oCd!5e0!3m2!1ses-419!2ssv!4v1785266083826!5m2!1ses-419!2ssv" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>',
  },
}

export const dashboardContent = {
  es: {
    admin: 'Dashboard administrador',
    user: 'Dashboard usuario',
    student: 'Dashboard estudiante',
    teacher: 'Dashboard docente',
    active: 'Sesión activa',
    messages: 'Mensajes',
    gallery: 'Galería',
    events: 'Noticias y eventos',
    profile: 'Perfil',
    userTab: 'Usuario',
    studentTab: 'Estudiante',
    teacherTab: 'Docente',
    role: 'Rol',
    noMessages: 'No hay mensajes registrados.',
    adminHelp: 'Desde aquí puedes editar imágenes de la galería y noticias o eventos.',
    userHelp: 'Área de usuario para ver avisos y enviar mensajes.',
    studentHelp: 'Espacio para avisos, mensajes y seguimiento del estudiante.',
    teacherHelp: 'Espacio para avisos docentes y gestión académica futura.',
    adminGalleryTitle: 'Editar imágenes de la galería',
    adminEventsTitle: 'Editar noticias y eventos',
    adminReviewsTitle: 'Gestionar reseñas',
    reviews: 'Reseñas',
    noReviews: 'No hay reseñas registradas.',
    editGalleryItem: 'Editar imagen',
    addGalleryItem: 'Agregar imagen',
    editEvent: 'Editar evento',
    addEvent: 'Agregar evento',
    noGalleryItems: 'No hay imágenes en la galería.',
    noEvents: 'No hay eventos registrados.',
    adminMessagesTitle: 'Mensajes de contacto',
    userMessagesTitle: 'Historial de mensajes',
  },
  en: {
    admin: 'Administrator dashboard',
    user: 'User dashboard',
    student: 'Student dashboard',
    teacher: 'Teacher dashboard',
    active: 'Active session',
    messages: 'Messages',
    gallery: 'Gallery',
    events: 'News and events',
    profile: 'Profile',
    userTab: 'User',
    studentTab: 'Student',
    teacherTab: 'Teacher',
    role: 'Role',
    noMessages: 'No messages registered.',
    adminHelp: 'From here you can edit gallery images and news/events.',
    userHelp: 'User space to see notices and send messages.',
    studentHelp: 'Area for student notices, messages and tracking.',
    teacherHelp: 'Area for teacher notices and future academic management.',
    adminGalleryTitle: 'Edit gallery images',
    adminEventsTitle: 'Edit news and events',
    adminReviewsTitle: 'Manage reviews',
    reviews: 'Reviews',
    noReviews: 'No reviews registered.',
    editGalleryItem: 'Edit image',
    addGalleryItem: 'Add image',
    editEvent: 'Edit event',
    addEvent: 'Add event',
    noGalleryItems: 'No gallery images available.',
    noEvents: 'No events registered.',
    adminMessagesTitle: 'Contact messages',
    userMessagesTitle: 'Message history',
  },
}

export const loginContent = {
  es: {
    title: 'Acceso al sistema',
    text: 'Ingresa como administrador, usuario, estudiante o docente.',
    password: 'Contraseña',
    submit: 'Iniciar sesión',
  },
  en: {
    title: 'System access',
    text: 'Sign in as administrator, user, student or teacher.',
    password: 'Password',
    submit: 'Sign in',
  },
}

export const servicesContent = {
  es: [
    ['Educación académica', 'Programas educativos rigurosos desde kínder hasta noveno grado.'],
    ['Actividades deportivas', 'Deporte y educación física para fomentar el trabajo en equipo.'],
    ['Artes y cultura', 'Música, arte y participación cívica.'],
    ['Consejería estudiantil', 'Orientación para estudiantes y familias.'],
  ],
  en: [
    ['Academic education', 'Rigorous educational programs from kindergarten to ninth grade.'],
    ['Sports activities', 'Sports and physical education for teamwork.'],
    ['Arts and culture', 'Music, art and civic participation.'],
    ['Student counseling', 'Guidance for students and families.'],
  ],
}

export function buildPublicTranslations(lang = 'es') {
  return {
    nav: navContent[lang],
    home: homeContent[lang],
    pages: pageContent[lang],
    forms: formContent[lang],
    dashboard: dashboardContent[lang],
    login: loginContent[lang],
  }
}
